version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      - mysql-data:/var/lib/mysql
  minio:
    command: server /data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    image: 'minio/minio'
    ports:
     - '${MINIO_PORT}:9000'
    volumes:
     - minio-data:/data
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - nginx-data:/data
      - certbot-data:/etc/letsencrypt
    depends_on:
      - db
volumes:
  certbot-data:
  minio-data:
  mysql-data:
  nginx-data:
