version: '3'
services:
  minio:
    command: server /data
    env_file: .env
    image: 'minio/minio'
    ports:
     - '${MINIO_PORT}:9000'
    volumes:
     - minio-data:/data
  nginx-cerbot:
    build: .
    ports:
     - '${NGINX_HTTP_PORT}:80'
     - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - certbot-data:/
      - nginx-data:/
volumes:
  certbot-data:
  minio-data:
  nginx-data:
